apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: reservation-service