apiVersion: v1
kind: Pod
metadata:
  name: postgres-reservation
  labels:
    app: postgres-reservation
spec:
  containers:
    - name: postgres-reservation
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: reservationdb
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-reservation
spec:
  selector:
    app: postgres-reservation
  ports:
    - port: 5432
      targetPort: 5432
