apiVersion: v1
kind: Pod
metadata:
  name: postgres-user
  labels:
    app: postgres-user
spec:
  containers:
    - name: postgres-user
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: userdb
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user
spec:
  selector:
    app: postgres-user
  ports:
    - port: 5432
      targetPort: 5432
