# helm/user-service/values.yaml
image:
  repository: marouamehrez09/user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

env:
  POSTGRES_HOST: postgres-user
  POSTGRES_PORT: "5432"
  POSTGRES_DB: user_db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: userpassword
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
serviceAccount:
  create: false
  name: ""
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: user.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

