# helm/user-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: user-service
